Hoteleria/grails-app/domain/hoteleria/User.groovy
package hoteleria

class User {
	String userName
	String password
	String email
	String address
	String telephone
	String rol

	static hasMany = [reserves:Reservation]
	static belongsTo = [reserves:Reservation]

	static constraints = {
		userName blank: false, size: 4..20
		password blank: false, password: true, size: 4..20
		email unique: true, blank: false, email:true
		telephone size: 7..15, matches: "[0-9|-]*"
		rol nullable:true
		//role inList:['Admin', 'User', 'Manager']
	}

	String toString(){
		"$userName"//"$role"+
	}
}

Hoteleria/grails-app/controllers/hoteleria/UserController.groovy
package hoteleria



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class UserController {

    static allowedMethods = [save: "POST", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond User.list(params), model:[userInstanceCount: User.count()]
    }

    def show(User userInstance) {
        respond userInstance
    }

    def create() {
        respond new User(params)
    }

    @Transactional
    def save(User userInstance) {
        if (userInstance == null) {
            notFound()
            return
        }

		userInstance.rol='User'
		
        if (userInstance.hasErrors()) {
            respond userInstance.errors, view:'create'
            return
        }

        userInstance.save(flush:true)
		
		
		redirect (controller:'Login',action: 'index', params:[mensaje: "Usuario creado correctamente!"])
		

//        request.withFormat {
//            form multipartForm {
//                flash.message = message(code: 'default.created.message', args: [message(code: 'user.label', default: 'User'), userInstance.id])
//                redirect userInstance
//            }
//            '*' { respond userInstance, [status: CREATED] }
//        }
		
    }

    def edit(User userInstance) {
        respond userInstance
    }

    @Transactional
    def update(User userInstance) {
        if (userInstance == null) {
            notFound()
            return
        }

        if (userInstance.hasErrors()) {
            respond userInstance.errors, view:'edit'
            return
        }

        userInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'User.label', default: 'User'), userInstance.id])
                redirect userInstance
            }
            '*'{ respond userInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(User userInstance) {

        if (userInstance == null) {
            notFound()
            return
        }

        userInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'User.label', default: 'User'), userInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'user.label', default: 'User'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

Hoteleria/grails-app/views/user/_form.gsp
<%@ page import="hoteleria.User"%>



<div
	class="fieldcontain ${hasErrors(bean: userInstance, field: 'userName', 'error')} required">
	<label for="userName"> <g:message code="user.userName.label"
			default="User Name" /> <span class="required-indicator">*</span>
	</label>
	<g:textField class="form-control" name="userName" maxlength="20"
		required="" value="${userInstance?.userName}" />

</div>

<div
	class="fieldcontain ${hasErrors(bean: userInstance, field: 'password', 'error')} required">
	<label for="password"> <g:message code="user.password.label"
			default="Password" /> <span class="required-indicator">*</span>
	</label>
	<g:field class="form-control" type="password" name="password"
		maxlength="20" required="" value="${userInstance?.password}" />

</div>

<div
	class="fieldcontain ${hasErrors(bean: userInstance, field: 'email', 'error')} required">
	<label for="email"> <g:message code="user.email.label"
			default="Email" /> <span class="required-indicator">*</span>
	</label>
	<g:field class="form-control" type="email" name="email" required=""
		value="${userInstance?.email}" />

</div>

<div
	class="fieldcontain ${hasErrors(bean: userInstance, field: 'adress', 'error')} required">
	<label for="adress"> <g:message code="user.adress.label"
			default="Address" /> <span class="required-indicator">*</span>
	</label>
	<g:textField class="form-control" name="address" required=""
		value="${userInstance?.address}" />

</div>

<%--<div--%>
<%--	class="fieldcontain ${hasErrors(bean: userInstance, field: 'reserves', 'error')} ">--%>
<%--	<label for="reserves"> <g:message code="user.reserves.label"--%>
<%--			default="Reserves" />--%>
<%----%>
<%--	</label>--%>
<%--	<ul class="one-to-many">--%>
<%--		<g:each in="${userInstance?.reserves?}" var="r">--%>
<%--			<li><g:link controller="reservation" action="show" id="${r.id}">--%>
<%--					${r?.encodeAsHTML()}--%>
<%--				</g:link></li>--%>
<%--		</g:each>--%>
<%--		<li class="add"><g:link controller="reservation" action="create"--%>
<%--				params="['user.id': userInstance?.id]">--%>
<%--				${message(code: 'default.add.label', args: [message(code: 'reservation.label', default: 'Reservation')])}--%>
<%--			</g:link></li>--%>
<%--	</ul>--%>
<%----%>
<%----%>
<%--</div>--%>

<div
	class="fieldcontain ${hasErrors(bean: userInstance, field: 'telephone', 'error')} required">
	<label for="telephone"> <g:message code="user.telephone.label"
			default="Telephone" /> <span class="required-indicator">*</span>
	</label>
	<g:textField class="form-control" name="telephone" required=""
		value="${userInstance?.telephone}" />

</div>

Hoteleria/grails-app/views/user/create.gsp
<!DOCTYPE html>
<html>
<head>
<meta name="layout" content="hoteleriaLayout">
<title>Registro de usuario</title>
</head>

<body>
	<section id="contact-page">
		<div class="container">
			<div class="center">
				<br /> <br />
				<h2>Registrate</h2>
				<p class="lead">Ingresa tus datos para registrarte</p>
				<p class="lead" style="color: red">
					<g:hasErrors bean="${userInstance}">
						<g:eachError bean="${userInstance}" var="error">
							<li style="color: red"
								<g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
									error="${error}" /></li>
						</g:eachError>
					</g:hasErrors>
				</p>
			</div>
			<div class="row contact-wrap">
				<div class="status alert alert-success" style="display: none"></div>
				<g:form url="[resource:userInstance, action:'save']"
					name="contact-form">
					<div class="col-sm-5 col-sm-offset-3">
						<g:render template="form" />
						<div class="form-group">
							<g:submitButton class="btn btn-primary btn-lg" name="create"
								value="Registrarse" />
						</div>
					</div>
				</g:form>
			</div>

			<!--/.row-->
		</div>
		<!--/.container-->
	</section>
	<!--/#contact-page-->

	<g:form id="formRegistro" name="formRegistro" controller="User"
		action="create" style="padding-left:5px">
	</g:form>
</body>

<%--	<body>--%>
<%--		<a href="#create-user" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>--%>
<%--		<div class="nav" role="navigation">--%>
<%--			<ul>--%>
<%--				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>--%>
<%--				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>--%>
<%--			</ul>--%>
<%--		</div>--%>
<%--		<div id="create-user" class="content scaffold-create" role="main">--%>
<%--			<h1><g:message code="default.create.label" args="[entityName]" /></h1>--%>
<%--			<g:if test="${flash.message}">--%>
<%--			<div class="message" role="status">${flash.message}</div>--%>
<%--			</g:if>--%>
<%--			<g:hasErrors bean="${userInstance}">--%>
<%--			<ul class="errors" role="alert">--%>
<%--				<g:eachError bean="${userInstance}" var="error">--%>
<%--				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>--%>
<%--				</g:eachError>--%>
<%--			</ul>--%>
<%--			</g:hasErrors>--%>
<%--			<g:form url="[resource:userInstance, action:'save']" method="POST">--%>
<%--				<fieldset class="form">--%>
<%--					<g:render template="form"/>--%>
<%--				</fieldset>--%>
<%--				<fieldset class="buttons">--%>
<%--					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />--%>
<%--				</fieldset>--%>
<%--			</g:form>--%>
<%--		</div>--%>
<%--	</body>--%>
</html>

Hoteleria/grails-app/views/user/edit.gsp
<%@ page import="hoteleria.User" %>
<!DOCTYPE html>
<html>

	<head>
		<meta name="layout" content="hoteleriaLayout">
		<g:set var="entityName" value="${message(code: 'user.label', default: 'User')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-user" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-user" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${userInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${userInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:userInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${userInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="btn btn-primary btn-lg" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

Hoteleria/grails-app/views/user/index.gsp
<%@ page import="hoteleria.User" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="hoteleriaLayout">
		<g:set var="entityName" value="${message(code: 'user.label', default: 'User')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<section id="contact-page">
		<div class="container">
			<div class="center">
				<br /> <br />
				<h2>Usuarios</h2>
				<p class="lead">Consulta los Usuarios</p>
		<div id="list-user" class="content scaffold-list" role="main">
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table border="1" style="text-align: center; width: 1000px">
			<thead>
					<tr>
					
						<g:sortableColumn property="userName" title="${message(code: 'user.userName.label', default: 'User Name')}" />
					
						<g:sortableColumn property="password" title="${message(code: 'user.password.label', default: 'Password')}" />
					
						<g:sortableColumn property="email" title="${message(code: 'user.email.label', default: 'Email')}" />
					
						<g:sortableColumn property="telephone" title="${message(code: 'user.telephone.label', default: 'Telephone')}" />
					
						<g:sortableColumn property="address" title="${message(code: 'user.address.label', default: 'Address')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${userInstanceList}" status="i" var="userInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${userInstance.id}">${fieldValue(bean: userInstance, field: "userName")}</g:link></td>
					
						<td>${fieldValue(bean: userInstance, field: "password")}</td>
					
						<td>${fieldValue(bean: userInstance, field: "email")}</td>
					
						<td>${fieldValue(bean: userInstance, field: "telephone")}</td>
					
						<td>${fieldValue(bean: userInstance, field: "address")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${userInstanceCount ?: 0}" />
			</div>
		</div>
		</div>
		</div>
	</section>
	</body>
</html>

Hoteleria/grails-app/views/user/show.gsp
<%@ page import="hoteleria.User"%>
<!DOCTYPE html>
<html>
<head>
<meta name="layout" content="hoteleriaLayout">
<g:set var="entityName"
	value="${message(code: 'user.label', default: 'User')}" />
<title><g:message code="default.show.label" args="[entityName]" /></title>
</head>
<body>
	<section id="contact-page">
		<div class="container">

			<div class="left">
				<br /> <br />
				<h2>Datos del Usuario</h2>
				<g:if test="${flash.message}">
					<div class="message" role="status">
						${flash.message}
					</div>
				</g:if>
				<ol class="property-list user">

					<g:if test="${userInstance?.userName}">
						<li class="fieldcontain"><span id="userName-label"
							class="property-label"><g:message
									code="user.userName.label" default="User Name" /></span> <span
							class="property-value" aria-labelledby="userName-label"><g:fieldValue
									bean="${userInstance}" field="userName" /></span></li>
					</g:if>

					<g:if test="${userInstance?.password}">
						<li class="fieldcontain"><span id="password-label"
							class="property-label"><g:message
									code="user.password.label" default="Password" /></span> <span
							class="property-value" aria-labelledby="password-label"><g:fieldValue
									bean="${userInstance}" field="password" /></span></li>
					</g:if>

					<g:if test="${userInstance?.email}">
						<li class="fieldcontain"><span id="email-label"
							class="property-label"><g:message code="user.email.label"
									default="Email" /></span> <span class="property-value"
							aria-labelledby="email-label"><g:fieldValue
									bean="${userInstance}" field="email" /></span></li>
					</g:if>

					<g:if test="${userInstance?.telephone}">
						<li class="fieldcontain"><span id="telephone-label"
							class="property-label"><g:message
									code="user.telephone.label" default="Telephone" /></span> <span
							class="property-value" aria-labelledby="telephone-label"><g:fieldValue
									bean="${userInstance}" field="telephone" /></span></li>
					</g:if>

					<g:if test="${userInstance?.address}">
						<li class="fieldcontain"><span id="address-label"
							class="property-label"><g:message
									code="user.address.label" default="Address" /></span> <span
							class="property-value" aria-labelledby="address-label"><g:fieldValue
									bean="${userInstance}" field="address" /></span></li>
					</g:if>

					<g:if test="${userInstance?.reserves}">
						<li class="fieldcontain"><span id="reserves-label"
							class="property-label"><g:message
									code="user.reserves.label" default="Reserves" /></span> <g:each
								in="${userInstance.reserves}" var="r">
								<span class="property-value" aria-labelledby="reserves-label"><g:link
										controller="reservation" action="show" id="${r.id}">
										${r?.encodeAsHTML()}
									</g:link></span>
							</g:each></li>
					</g:if>

				</ol>
				<g:form url="[resource:userInstance, action:'delete']"
					method="DELETE">
					<fieldset class="buttons">
						<g:if test="${session.rol == 'Admin'}">
							<g:link class="edit" action="edit" resource="${userInstance}">
								<g:message code="default.button.edit.label" default="Edit" />
							</g:link>
						</g:if>
						<%--					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />--%>
					</fieldset>
				</g:form>
			</div>
		</div>
	</section>
</body>
</html>