Hoteleria/grails-app/domain/hoteleria/Reservation.groovy
package hoteleria

class Reservation {

	Integer idReserv
	float totalPriceReserv
	String pay
	Date emisionDateReserv
	Date invalidDateReserv
	Hotel hotel
	User user
	
	static hasMany=[rooms: Room]

	static constraints = {
		idReserv unique:true
		emisionDateReserv min:new Date()
		//		invalidDateReserv min: emisionDateReserv
		invalidDateReserv(validator: { val, obj ->
			val?.after(obj.emisionDateReserv)
		})
		totalPriceReserv min:0F
		pay inList:["Efecty", "Credit Card", "Debit Card", "Checks"]
	}
	
}

Hoteleria/grails-app/controllers/hoteleria/ReservationController.groovy
package hoteleria



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class ReservationController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Reservation.list(params), model:[reservationInstanceCount: Reservation.count()]
    }

    def show(Reservation reservationInstance) {
        respond reservationInstance
    }

    def create() {
        respond new Reservation(params)
    }

    @Transactional
    def save(Reservation reservationInstance) {
        if (reservationInstance == null) {
            notFound()
            return
        }

        if (reservationInstance.hasErrors()) {
            respond reservationInstance.errors, view:'create'
            return
        }

        reservationInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'reservation.label', default: 'Reservation'), reservationInstance.id])
                redirect reservationInstance
            }
            '*' { respond reservationInstance, [status: CREATED] }
        }
    }

    def edit(Reservation reservationInstance) {
        respond reservationInstance
    }

    @Transactional
    def update(Reservation reservationInstance) {
        if (reservationInstance == null) {
            notFound()
            return
        }

        if (reservationInstance.hasErrors()) {
            respond reservationInstance.errors, view:'edit'
            return
        }

        reservationInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'Reservation.label', default: 'Reservation'), reservationInstance.id])
                redirect reservationInstance
            }
            '*'{ respond reservationInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(Reservation reservationInstance) {

        if (reservationInstance == null) {
            notFound()
            return
        }

        reservationInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Reservation.label', default: 'Reservation'), reservationInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'reservation.label', default: 'Reservation'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

Hoteleria/grails-app/views/reservation/_form.gsp
<%@ page import="hoteleria.Reservation" %>



<div class="fieldcontain ${hasErrors(bean: reservationInstance, field: 'idReserv', 'error')} required">
	<label for="idReserv">
		<g:message code="reservation.idReserv.label" default="Id Reserv" />
		<span class="required-indicator">*</span>
	</label>
	<g:field class="form-control" name="idReserv" type="number" value="${reservationInstance.idReserv}" required=""/>

</div>

<div class="fieldcontain ${hasErrors(bean: reservationInstance, field: 'emisionDateReserv', 'error')} required">
	<label for="emisionDateReserv">
		<g:message code="reservation.emisionDateReserv.label" default="Emision Date Reserv" />
		<span class="required-indicator">*</span>
	</label>
	<g:datePicker class="form-control" name="emisionDateReserv" precision="day"  value="${reservationInstance?.emisionDateReserv}"  />

</div>

<div class="fieldcontain ${hasErrors(bean: reservationInstance, field: 'invalidDateReserv', 'error')} required">
	<label for="invalidDateReserv">
		<g:message code="reservation.invalidDateReserv.label" default="Invalid Date Reserv" />
		<span class="required-indicator">*</span>
	</label>
	<g:datePicker class="form-control" name="invalidDateReserv" precision="day"  value="${reservationInstance?.invalidDateReserv}"  />

</div>

<div class="fieldcontain ${hasErrors(bean: reservationInstance, field: 'totalPriceReserv', 'error')} required">
	<label for="totalPriceReserv">
		<g:message code="reservation.totalPriceReserv.label" default="Total Price Reserv" />
		<span class="required-indicator">*</span>
	</label>
	<g:field class="form-control" name="totalPriceReserv" value="${fieldValue(bean: reservationInstance, field: 'totalPriceReserv')}" required=""/>

</div>

<div class="fieldcontain ${hasErrors(bean: reservationInstance, field: 'pay', 'error')} required">
	<label for="pay">
		<g:message code="reservation.pay.label" default="Pay" />
		<span class="required-indicator">*</span>
	</label>
	<g:select class="form-control" name="pay" from="${reservationInstance.constraints.pay.inList}" required="" value="${reservationInstance?.pay}" valueMessagePrefix="reservation.pay"/>

</div>

<div class="fieldcontain ${hasErrors(bean: reservationInstance, field: 'hotel', 'error')} required">
	<label for="hotel">
		<g:message code="reservation.hotel.label" default="Hotel" />
		<span class="required-indicator">*</span>
	</label>
	<g:select class="form-control" id="hotel" name="hotel.id" from="${hoteleria.Hotel.list()}" optionKey="id" required="" value="${reservationInstance?.hotel?.id}" class="many-to-one"/>

</div>

<div class="fieldcontain ${hasErrors(bean: reservationInstance, field: 'user', 'error')} required">
	<label for="user">
		<g:message code="reservation.user.label" default="User" />
		<span class="required-indicator">*</span>
	</label>
	<g:select class="form-control" id="user" name="user.id" from="${hoteleria.User.list()}" optionKey="id" required="" value="${reservationInstance?.user?.id}" class="many-to-one"/>
<%--<input type="hidden" id="user" name="user.id" value="${session.userid }">--%>
</div>

Hoteleria/grails-app/views/reservation/create.gsp
<!DOCTYPE html>
<html>
<head>
<meta name="layout" content="hoteleriaLayout">
<g:set var="entityName"
	value="${message(code: 'reservation.label', default: 'Reservation')}" />
<title><g:message code="default.create.label"
		args="[entityName]" /></title>
</head>
<body>
	<section id="contact-page">
		<div class="container">
			<div class="center">
				<br /> <br />
				<h2>Crear Reservacion</h2>
				<p class="lead">Ingresa los datos de la reservacion</p>
				<p class="lead" style="color: red">
					<g:hasErrors bean="${reservationInstance}">
						<ul class="errors" role="alert">
							<g:eachError bean="${reservationInstance}" var="error">
								<li
									<g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
										error="${error}" /></li>
							</g:eachError>
						</ul>
					</g:hasErrors>
				</p>
			</div>
			<div class="row contact-wrap">
				<div class="status alert alert-success" style="display: none"></div>
				<g:form url="[resource:reservationInstance, action:'save']">
					<div class="col-sm-5 col-sm-offset-3">
						<g:render template="form" />
						<div class="form-group">
							<g:submitButton name="create" class="btn btn-primary btn-lg"
								value="${message(code: 'default.button.create.label', default: 'Create')}" />
						</div>
					</div>
				</g:form>
			</div>
		</div>
	</section>
</body>
</html>

Hoteleria/grails-app/views/reservation/edit.gsp
<%@ page import="hoteleria.Reservation"%>
<!DOCTYPE html>
<html>
<head>
<meta name="layout" content="hoteleriaLayout">
<g:set var="entityName"
	value="${message(code: 'reservation.label', default: 'Reservation')}" />
<title><g:message code="default.edit.label" args="[entityName]" /></title>
</head>
<body>
	<section id="contact-page">
		<div class="container">
			<div class="center">
				<br /> <br />
				<h2>Actualizar Reservacion</h2>
				<p class="lead">Ingresa los datos de la reservacion</p>
				<p class="lead" style="color: red">
					<g:hasErrors bean="${reservationInstance}">
						<ul class="errors" role="alert">
							<g:eachError bean="${reservationInstance}" var="error">
								<li
									<g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
										error="${error}" /></li>
							</g:eachError>
						</ul>
					</g:hasErrors>
				</p>
			</div>


			<div class="row contact-wrap">
				<div class="status alert alert-success" style="display: none"></div>
				<g:form url="[resource:reservationInstance, action:'update']"
					method="PUT">
					<g:hiddenField name="version"
						value="${reservationInstance?.version}" />
					<div class="col-sm-5 col-sm-offset-3">
						<g:render template="form" />
						<div class="form-group">
							<g:actionSubmit class="btn btn-primary btn-lg" action="update"
								value="${message(code: 'default.button.update.label', default: 'Update')}" />
						</div>
					</div>
				</g:form>
			</div>
		</div>
	</section>
</body>
</html>

Hoteleria/grails-app/views/reservation/index.gsp
<%@ page import="hoteleria.Reservation" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="hoteleriaLayout">
		<g:set var="entityName" value="${message(code: 'reservation.label', default: 'Reservation')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<section id="contact-page">
		<div class="container">
			<div class="center">
				<br /> <br />
				<h2>Reservaciones</h2>
				<p class="lead">Consulta las Reservaciones</p>
		<div id="list-reservation" class="content scaffold-list" role="main">
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table border="1" style="text-align: center; width: 1000px">
			<thead>
					<tr>
					
						<g:sortableColumn property="idReserv" title="${message(code: 'reservation.idReserv.label', default: 'Id Reserv')}" />
					
						<g:sortableColumn property="emisionDateReserv" title="${message(code: 'reservation.emisionDateReserv.label', default: 'Emision Date Reserv')}" />
					
						<g:sortableColumn property="invalidDateReserv" title="${message(code: 'reservation.invalidDateReserv.label', default: 'Invalid Date Reserv')}" />
					
						<g:sortableColumn property="totalPriceReserv" title="${message(code: 'reservation.totalPriceReserv.label', default: 'Total Price Reserv')}" />
					
						<g:sortableColumn property="pay" title="${message(code: 'reservation.pay.label', default: 'Pay')}" />
					
						<th><g:message code="reservation.hotel.label" default="Hotel" /></th>
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${reservationInstanceList}" status="i" var="reservationInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${reservationInstance.id}">${fieldValue(bean: reservationInstance, field: "idReserv")}</g:link></td>
					
						<td><g:formatDate date="${reservationInstance.emisionDateReserv}" /></td>
					
						<td><g:formatDate date="${reservationInstance.invalidDateReserv}" /></td>
					
						<td>${fieldValue(bean: reservationInstance, field: "totalPriceReserv")}</td>
					
						<td>${fieldValue(bean: reservationInstance, field: "pay")}</td>
					
						<td>${fieldValue(bean: reservationInstance, field: "hotel")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${reservationInstanceCount ?: 0}" />
			</div>
		</div>
		</div>
		</div>
	</section>
	</body>
</html>

Hoteleria/grails-app/views/reservation/show.gsp
<%@ page import="hoteleria.Reservation"%>
<!DOCTYPE html>
<html>
<head>
<meta name="layout" content="hoteleriaLayout">
<g:set var="entityName"
	value="${message(code: 'reservation.label', default: 'Reservation')}" />
<title><g:message code="default.show.label" args="[entityName]" /></title>
</head>
<body>
	<section id="contact-page">
		<div class="container">

			<div class="left">
				<br /> <br />
				<h2>Datos de la Reservacion</h2>
				<g:if test="${flash.message}">
					<div class="message" role="status">
						${flash.message}
					</div>
				</g:if>
				<ol class="property-list reservation">

					<g:if test="${reservationInstance?.idReserv}">
						<li class="fieldcontain"><span id="idReserv-label"
							class="property-label"><g:message
									code="reservation.idReserv.label" default="Id Reserv" /></span> <span
							class="property-value" aria-labelledby="idReserv-label"><g:fieldValue
									bean="${reservationInstance}" field="idReserv" /></span></li>
					</g:if>

					<g:if test="${reservationInstance?.emisionDateReserv}">
						<li class="fieldcontain"><span id="emisionDateReserv-label"
							class="property-label"><g:message
									code="reservation.emisionDateReserv.label"
									default="Emision Date Reserv" /></span> <span class="property-value"
							aria-labelledby="emisionDateReserv-label"><g:formatDate
									date="${reservationInstance?.emisionDateReserv}" /></span></li>
					</g:if>

					<g:if test="${reservationInstance?.invalidDateReserv}">
						<li class="fieldcontain"><span id="invalidDateReserv-label"
							class="property-label"><g:message
									code="reservation.invalidDateReserv.label"
									default="Invalid Date Reserv" /></span> <span class="property-value"
							aria-labelledby="invalidDateReserv-label"><g:formatDate
									date="${reservationInstance?.invalidDateReserv}" /></span></li>
					</g:if>

					<g:if test="${reservationInstance?.totalPriceReserv}">
						<li class="fieldcontain"><span id="totalPriceReserv-label"
							class="property-label"><g:message
									code="reservation.totalPriceReserv.label"
									default="Total Price Reserv" /></span> <span class="property-value"
							aria-labelledby="totalPriceReserv-label"><g:fieldValue
									bean="${reservationInstance}" field="totalPriceReserv" /></span></li>
					</g:if>

					<g:if test="${reservationInstance?.pay}">
						<li class="fieldcontain"><span id="pay-label"
							class="property-label"><g:message
									code="reservation.pay.label" default="Pay" /></span> <span
							class="property-value" aria-labelledby="pay-label"><g:fieldValue
									bean="${reservationInstance}" field="pay" /></span></li>
					</g:if>

					<g:if test="${reservationInstance?.hotel}">
						<li class="fieldcontain"><span id="hotel-label"
							class="property-label"><g:message
									code="reservation.hotel.label" default="Hotel" /></span> <span
							class="property-value" aria-labelledby="hotel-label"><g:link
									controller="hotel" action="show"
									id="${reservationInstance?.hotel?.id}">
									${reservationInstance?.hotel?.encodeAsHTML()}
								</g:link></span></li>
					</g:if>

					<g:if test="${reservationInstance?.user}">
						<li class="fieldcontain"><span id="user-label"
							class="property-label"><g:message
									code="reservation.user.label" default="User" /></span> <span
							class="property-value" aria-labelledby="user-label"><g:link
									controller="user" action="show"
									id="${reservationInstance?.user?.id}">
									${reservationInstance?.user?.encodeAsHTML()}
								</g:link></span></li>
					</g:if>

				</ol>
				<g:form url="[resource:reservationInstance, action:'delete']"
					method="DELETE">
					<fieldset class="buttons">
						<g:if test="${session.rol == 'Admin'}">
							<g:link class="edit" action="edit"
								resource="${reservationInstance}">
								<g:message code="default.button.edit.label" default="Edit" />
							</g:link>
						</g:if>
						<%--					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />--%>
					</fieldset>
				</g:form>
			</div>
		</div>
	</section>
</body>
</html>